language: node_js
node_js:
  - '0.10'
before_install:
  - 'gem install compass'
  - 'gem uninstall sass -I --no-executables'
  - 'gem install sass --version 3.2.12'
before_script:
  - 'npm install  -g bower grunt-cli'
  - 'bower install'
script: grunt test --verbose --force

