language: node_js
node_js:
  - '0.10'
before_install:
  - 'gem install compass'
  - 'gem uninstall sass --force --no-abort-on-dependent'
  - 'gem install sass --version 3.2.13'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
